import type { Answer, CaseRecord, MedicalDocument, RedFlag, SectionId } from "./types";

const answer = (
  questionId: string,
  section: SectionId,
  question: string,
  value: string,
): Answer => ({
  questionId,
  section,
  question,
  value,
  answeredAt: "2026-09-12T09:10:00.000Z",
});

const meeraDocs: MedicalDocument[] = [
  {
    id: "doc-m1",
    fileName: "lab-report-12sep2026.jpg",
    kind: "Lab report",
    documentDate: "12 Sep 2026",
    facility: "Sanjivani Diagnostics, Nagpur",
    status: "extracted",
    fields: [
      { label: "Document date", value: "12 Sep 2026", confidence: "High" },
      { label: "HbA1c", value: "8.4 %", confidence: "High" },
      { label: "Fasting glucose", value: "168 mg/dL", confidence: "High" },
      { label: "Serum creatinine", value: "1.3 mg/dL", confidence: "Medium" },
      { label: "NT-proBNP", value: "742 pg/mL", confidence: "Needs Review" },
      { label: "Ordering doctor", value: "Dr. A. Kulkarni", confidence: "Medium" },
    ],
  },
  {
    id: "doc-m2",
    fileName: "prescription-04aug2026.pdf",
    kind: "Prescription",
    documentDate: "04 Aug 2026",
    facility: "City Care Clinic, Nagpur",
    status: "extracted",
    fields: [
      { label: "Document date", value: "04 Aug 2026", confidence: "High" },
      { label: "Recorded diagnosis", value: "Type 2 diabetes, hypertension", confidence: "High" },
      { label: "Medicine", value: "Metformin 500 mg — twice daily", confidence: "High" },
      { label: "Medicine", value: "Amlodipine 5 mg — once daily", confidence: "High" },
      { label: "Allergy mention", value: "Sulpha medicines — rash", confidence: "Needs Review" },
      { label: "Doctor / hospital", value: "Dr. S. Rao, City Care Clinic", confidence: "Medium" },
    ],
  },
  {
    id: "doc-m3",
    fileName: "discharge-19mar2024.pdf",
    kind: "Discharge summary",
    documentDate: "19 Mar 2024",
    facility: "Government General Hospital, Nagpur",
    status: "extracted",
    fields: [
      { label: "Document date", value: "19 Mar 2024", confidence: "High" },
      { label: "Reason for admission", value: "Uncontrolled blood sugar", confidence: "Medium" },
      { label: "Length of stay", value: "4 days", confidence: "High" },
      { label: "Discharge medicines", value: "Metformin, Telmisartan", confidence: "Medium" },
    ],
  },
];

const meeraRedFlags: RedFlag[] = [
  {
    id: "chest-pain",
    label: "Severe chest pain or tightness",
    detail: "Patient described chest tightness worsening over four days.",
    source: "Patient interview — 'What brings you to the hospital today?'",
    severity: "urgent",
    detectedAt: "2026-09-12T09:12:00.000Z",
  },
  {
    id: "breathing",
    label: "Difficulty breathing",
    detail: "Patient reported shortness of breath on walking and at night.",
    source: "Patient interview — follow-up questions",
    severity: "urgent",
    detectedAt: "2026-09-12T09:13:00.000Z",
  },
];

export const MEERA: CaseRecord = {
  id: "case-meera",
  language: "hi",
  consentGiven: true,
  status: "submitted",
  createdAt: "2026-09-12T09:05:00.000Z",
  queueTime: "09:05 AM",
  profile: {
    name: "Meera Sharma",
    age: "54",
    gender: "female",
    mobile: "98220 41127",
    city: "Nagpur",
    abhaId: "12-3456-7890-1234",
    emergencyContact: "Rajesh Sharma — 98220 41128",
  },
  documents: meeraDocs,
  redFlags: meeraRedFlags,
  answers: [
    answer(
      "chief-complaint",
      "presenting",
      "What brings you to the hospital today?",
      "Chest tightness and shortness of breath while walking",
    ),
    answer("onset", "presenting", "When did this problem start?", "About 4 days ago"),
    answer("location", "presenting", "Where do you feel the problem?", "Chest, spreading to back"),
    answer("severity", "presenting", "How severe is it on a scale of 1 to 10?", "7"),
    answer("trend", "presenting", "Is it getting better, worse, or staying the same?", "Getting worse"),
    answer(
      "fu-exertion",
      "presenting",
      "Does it get worse when you walk or climb stairs?",
      "Yes, much worse",
    ),
    answer("fu-swelling", "presenting", "Have your feet or ankles been swelling?", "Yes, in the evening"),
    answer("fu-night", "presenting", "Do you wake up at night feeling breathless?", "Yes"),
    answer(
      "past-illness",
      "history",
      "Do you have any long-standing health problems?",
      "Diabetes (12 years), high blood pressure (6 years)",
    ),
    answer(
      "hospitalisation",
      "history",
      "Have you ever stayed in a hospital overnight?",
      "Yes — 4 days in March 2024 for high sugar",
    ),
    answer("surgery", "surgeries", "Have you had any operations before?", "Caesarean section, 1998"),
    answer(
      "medicines",
      "medicines",
      "Which medicines do you take regularly?",
      "Metformin 500 mg, Amlodipine 5 mg",
    ),
    answer("dosage", "medicines", "How many times a day do you take them?", "Metformin twice, Amlodipine once"),
    answer("allergies", "medicines", "Does any medicine or food cause you problems?", "Sulpha medicines — rash"),
    answer(
      "family",
      "family",
      "Do close family members have any health problems?",
      "Father had heart disease, mother had diabetes",
    ),
    answer("smoking", "lifestyle", "Do you smoke or chew tobacco?", "Never"),
    answer("alcohol", "lifestyle", "Do you drink alcohol?", "Never"),
    answer("diet", "lifestyle", "What kind of food do you usually eat?", "Vegetarian, home cooked"),
    answer("sleep", "lifestyle", "How well do you sleep at night?", "Wakes up often, needs 2 pillows"),
    answer("activity", "lifestyle", "How active are you during the day?", "Light housework only"),
    answer("menstrual", "womens", "How are your monthly periods these days?", "Stopped (menopause) since 2018"),
    answer("pregnancy", "womens", "Are you pregnant, or could you be pregnant?", "No"),
    answer("obstetric", "womens", "How many children have you had?", "Two"),
    answer("prakriti", "ayurveda", "Optional: how would you describe your body type (Prakriti)?", "Kapha (heavy, calm)"),
    answer("agni", "ayurveda", "Optional: how is your digestion and appetite (Agni)?", "Heaviness after food"),
  ],
};

export const RAHUL: CaseRecord = {
  id: "case-rahul",
  language: "en",
  consentGiven: true,
  status: "submitted",
  createdAt: "2026-09-12T09:40:00.000Z",
  queueTime: "09:40 AM",
  profile: {
    name: "Rahul Verma",
    age: "27",
    gender: "male",
    mobile: "99101 22874",
    city: "Pune",
    abhaId: "",
    emergencyContact: "Neha Verma — 99101 22875",
  },
  redFlags: [],
  documents: [
    {
      id: "doc-r1",
      fileName: "cbc-11sep2026.jpg",
      kind: "Lab report",
      documentDate: "11 Sep 2026",
      facility: "Pune Path Labs",
      status: "extracted",
      fields: [
        { label: "Document date", value: "11 Sep 2026", confidence: "High" },
        { label: "Haemoglobin", value: "14.2 g/dL", confidence: "High" },
        { label: "Total WBC", value: "11,800 /µL", confidence: "Medium" },
        { label: "Platelets", value: "2.1 lakh /µL", confidence: "High" },
        { label: "Lab / doctor", value: "Pune Path Labs", confidence: "Medium" },
      ],
    },
  ],
  answers: [
    answer(
      "chief-complaint",
      "presenting",
      "What brings you to the hospital today?",
      "Fever, sore throat and headache for two days",
    ),
    answer("onset", "presenting", "When did this problem start?", "2 days ago"),
    answer("location", "presenting", "Where do you feel the problem?", "Throat and forehead"),
    answer("severity", "presenting", "How severe is it on a scale of 1 to 10?", "5"),
    answer("trend", "presenting", "Is it getting better, worse, or staying the same?", "Staying the same"),
    answer("fu-fever-pattern", "presenting", "Is the fever there all day or does it come and go?", "Comes in the evening"),
    answer("fu-throat", "presenting", "Is it painful to swallow food or water?", "A little"),
    answer("fu-contact", "presenting", "Is anyone at home having the same problem?", "Yes, brother had fever last week"),
    answer("past-illness", "history", "Do you have any long-standing health problems?", "None of these"),
    answer("hospitalisation", "history", "Have you ever stayed in a hospital overnight?", "No, never"),
    answer("surgery", "surgeries", "Have you had any operations before?", "No operations"),
    answer("medicines", "medicines", "Which medicines do you take regularly?", "Paracetamol when needed"),
    answer("dosage", "medicines", "How many times a day do you take them?", "Twice a day for 2 days"),
    answer("allergies", "medicines", "Does any medicine or food cause you problems?", "No known allergy"),
    answer("family", "family", "Do close family members have any health problems?", "Father has blood pressure"),
    answer("smoking", "lifestyle", "Do you smoke or chew tobacco?", "Never"),
    answer("alcohol", "lifestyle", "Do you drink alcohol?", "Occasionally"),
    answer("diet", "lifestyle", "What kind of food do you usually eat?", "Mixed, mostly outside food"),
    answer("sleep", "lifestyle", "How well do you sleep at night?", "Sleep well"),
    answer("activity", "lifestyle", "How active are you during the day?", "Walking daily"),
  ],
};

export const DEMO_CASES: CaseRecord[] = [MEERA, RAHUL];

export const MOCK_OCR_TEMPLATES: Record<string, MedicalDocument["fields"]> = {
  Prescription: [
    { label: "Document date", value: "02 Sep 2026", confidence: "High" },
    { label: "Recorded diagnosis", value: "Acute pharyngitis", confidence: "Medium" },
    { label: "Medicine", value: "Amoxicillin 500 mg — three times daily, 5 days", confidence: "High" },
    { label: "Medicine", value: "Paracetamol 650 mg — when fever", confidence: "High" },
    { label: "Allergy mention", value: "None recorded on slip", confidence: "Needs Review" },
    { label: "Doctor / hospital", value: "Dr. P. Menon, Lotus Polyclinic", confidence: "Medium" },
  ],
  "Lab report": [
    { label: "Document date", value: "08 Sep 2026", confidence: "High" },
    { label: "Haemoglobin", value: "12.6 g/dL", confidence: "High" },
    { label: "Fasting glucose", value: "154 mg/dL", confidence: "Medium" },
    { label: "Serum creatinine", value: "1.1 mg/dL", confidence: "Needs Review" },
    { label: "Lab / doctor", value: "Sanjivani Diagnostics", confidence: "Medium" },
  ],
  "Discharge summary": [
    { label: "Document date", value: "21 Jun 2025", confidence: "High" },
    { label: "Reason for admission", value: "Dehydration with vomiting", confidence: "Medium" },
    { label: "Length of stay", value: "2 days", confidence: "High" },
    { label: "Discharge medicines", value: "ORS, Pantoprazole 40 mg", confidence: "Needs Review" },
    { label: "Doctor / hospital", value: "Govt. General Hospital", confidence: "Medium" },
  ],
};
