/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ConsentRouteImport } from './routes/consent'
import { Route as DoctorRouteImport } from './routes/doctor'
import { Route as DoctorDemoRouteImport } from './routes/doctor-demo'
import { Route as DocumentsRouteImport } from './routes/documents'
import { Route as InterviewRouteImport } from './routes/interview'
import { Route as ReviewRouteImport } from './routes/review'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsentRoute = ConsentRouteImport.update({
  id: '/consent',
  path: '/consent',
  getParentRoute: () => rootRouteImport,
} as any)
const DoctorRoute = DoctorRouteImport.update({
  id: '/doctor',
  path: '/doctor',
  getParentRoute: () => rootRouteImport,
} as any)
const DoctorDemoRoute = DoctorDemoRouteImport.update({
  id: '/doctor-demo',
  path: '/doctor-demo',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentsRoute = DocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => rootRouteImport,
} as any)
const InterviewRoute = InterviewRouteImport.update({
  id: '/interview',
  path: '/interview',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewRoute = ReviewRouteImport.update({
  id: '/review',
  path: '/review',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/consent': typeof ConsentRoute
  '/doctor': typeof DoctorRoute
  '/doctor-demo': typeof DoctorDemoRoute
  '/documents': typeof DocumentsRoute
  '/interview': typeof InterviewRoute
  '/review': typeof ReviewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/consent': typeof ConsentRoute
  '/doctor': typeof DoctorRoute
  '/doctor-demo': typeof DoctorDemoRoute
  '/documents': typeof DocumentsRoute
  '/interview': typeof InterviewRoute
  '/review': typeof ReviewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/consent': typeof ConsentRoute
  '/doctor': typeof DoctorRoute
  '/doctor-demo': typeof DoctorDemoRoute
  '/documents': typeof DocumentsRoute
  '/interview': typeof InterviewRoute
  '/review': typeof ReviewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/consent'
    | '/doctor'
    | '/doctor-demo'
    | '/documents'
    | '/interview'
    | '/review'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/consent'
    | '/doctor'
    | '/doctor-demo'
    | '/documents'
    | '/interview'
    | '/review'
  id:
    | '__root__'
    | '/'
    | '/consent'
    | '/doctor'
    | '/doctor-demo'
    | '/documents'
    | '/interview'
    | '/review'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ConsentRoute: typeof ConsentRoute
  DoctorRoute: typeof DoctorRoute
  DoctorDemoRoute: typeof DoctorDemoRoute
  DocumentsRoute: typeof DocumentsRoute
  InterviewRoute: typeof InterviewRoute
  ReviewRoute: typeof ReviewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/consent': {
      id: '/consent'
      path: '/consent'
      fullPath: '/consent'
      preLoaderRoute: typeof ConsentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/doctor': {
      id: '/doctor'
      path: '/doctor'
      fullPath: '/doctor'
      preLoaderRoute: typeof DoctorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/doctor-demo': {
      id: '/doctor-demo'
      path: '/doctor-demo'
      fullPath: '/doctor-demo'
      preLoaderRoute: typeof DoctorDemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/documents': {
      id: '/documents'
      path: '/documents'
      fullPath: '/documents'
      preLoaderRoute: typeof DocumentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/interview': {
      id: '/interview'
      path: '/interview'
      fullPath: '/interview'
      preLoaderRoute: typeof InterviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/review': {
      id: '/review'
      path: '/review'
      fullPath: '/review'
      preLoaderRoute: typeof ReviewRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ConsentRoute: ConsentRoute,
  DoctorRoute: DoctorRoute,
  DoctorDemoRoute: DoctorDemoRoute,
  DocumentsRoute: DocumentsRoute,
  InterviewRoute: InterviewRoute,
  ReviewRoute: ReviewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
